[versions]
agp = "8.9.1"
kotlin = "2.0.21"
sqldelight = "2.0.2"
kapt = "2.1.20"
hiltPlugin = "2.51.1"
navigation = "2.8.9"
appcompat = "1.7.0"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
coroutinesExtensions = "2.0.2"
androidDriver = "2.0.2"
espressoCore = "3.6.1"
fragmentKtx = "1.8.6"
hiltCompiler = "2.56.1"
junit = "4.13.2"
junitVersion = "1.2.1"
logcat = "0.1"
material = "1.12.0"
swiperefreshlayout = "1.1.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.00"

[libraries]
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "androidDriver" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "coroutinesExtensions" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltCompiler" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
cash-sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
