package me.elmanss.melate.common.util

object TestTags {
  // SHARED
  const val SHARED_TOP_BAR = "SHARED_TOP_BAR"
  const val SHARED_FAB_MAIN = "SHARED_FAB_MAIN"
  const val SHARED_DIALOG_CONTAINER = "SHARED_DIALOG_CONTAINER"
  const val SHARED_DIALOG_CONFIRM_BTN = "SHARED_DIALOG_CONFIRM_BTN"
  const val SHARED_EXTENDED_FAB_EXPAND = "SHARED_EXTENDED_FAB_EXPAND"
  const val SHARED_EXTENDED_FAB_ACTION_1 = "SHARED_EXTENDED_FAB_ACTION_1"
  const val SHARED_EXTENDED_FAB_ACTION_2 = "SHARED_EXTENDED_FAB_ACTION_2"

  // FAV_ITEM
  const val FAV_ITEM_ROW = "FAV_ITEM_ROW"
  const val FAV_ITEM_SUBMISSION_TOGGLE = "FAV_ITEM_SUBMISSION_TOGGLE"
  const val FAV_ITEM_CHECKBOX = "FAV_ITEM_CHECKBOX"
  const val FAV_ITEM_ORIGIN_ICON = "FAV_ITEM_ORIGIN_ICON"

  // HOME
  const val HOME_PULL_REFRESH = "HOME_PULL_REFRESH"
  const val HOME_SAVE_TOPBAR_ICON = "HOME_SAVE_TOPBAR_ICON"
  const val HOME_ITEM_ROW = "HOME_ITEM_ROW"
  const val HOME_ITEM_CHECKBOX = "HOME_ITEM_CHECKBOX"

  // CREATE_FAV
  const val CREATE_INPUT_DISPLAY = "CREATE_INPUT_DISPLAY"
  const val CREATE_NUMPAD_0 = "CREATE_NUMPAD_0"
  const val CREATE_NUMPAD_1 = "CREATE_NUMPAD_1"
  const val CREATE_NUMPAD_2 = "CREATE_NUMPAD_2"
  const val CREATE_NUMPAD_3 = "CREATE_NUMPAD_3"
  const val CREATE_NUMPAD_4 = "CREATE_NUMPAD_4"
  const val CREATE_NUMPAD_5 = "CREATE_NUMPAD_5"
  const val CREATE_NUMPAD_6 = "CREATE_NUMPAD_6"
  const val CREATE_NUMPAD_7 = "CREATE_NUMPAD_7"
  const val CREATE_NUMPAD_8 = "CREATE_NUMPAD_8"
  const val CREATE_NUMPAD_9 = "CREATE_NUMPAD_9"
  const val CREATE_KEY_BACKSPACE = "CREATE_KEY_BACKSPACE"
  const val CREATE_KEY_NEXT = "CREATE_KEY_NEXT"

  // LIST_FAVS
  const val LIST_EMPTY_STATE_CONTAINER = "LIST_EMPTY_STATE_CONTAINER"
  const val LIST_MULTI_DELETE_ICON = "LIST_MULTI_DELETE_ICON"
}
