package me.elmanss.melate.favorites.domain.usecase.impl

import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.impl.annotations.MockK
import io.mockk.junit5.MockKExtension
import kotlinx.coroutines.test.runTest
import me.elmanss.melate.common.data.local.FavOrigin
import me.elmanss.melate.common.domain.repository.FavoritosRepository
import me.elmanss.melate.favorites.domain.model.FavoritoModel
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(MockKExtension::class)
class AddFavoriteUseCaseTest {

  @MockK private lateinit var repository: FavoritosRepository
  private lateinit var useCase: AddFavoriteUseCase

  @BeforeEach
  fun setUp() {
    useCase = AddFavoriteUseCase(repository)
  }

  @Test
  fun `SHOULD call repository create WHEN use case is invoked`() = runTest {
    // GIVEN
    val model =
      FavoritoModel(
        id = 0, // ID is auto-generated by DB
        sorteo = "1,2,3,4,5,6",
        origin = FavOrigin.Manual,
        createdAt = 123456789L,
        isSubmitted = false,
      )
    coEvery { repository.createFavoritos(any(), any(), any()) } returns Unit

    // WHEN
    useCase(model)

    // THEN
    coVerify {
      repository.createFavoritos(
        sorteoString = model.sorteo,
        origin = model.origin,
        createdAt = model.createdAt,
      )
    }
  }
}
